[package]
name = "dragonfly"
version = "0.1.0"
edition = "2021"


[profile.release]
lto = true
panic = "abort"
debug = true
codegen-units = 1

[dependencies]
libafl = "0.10.1"
nix = "0.26"
libc = "0.2"
serde = "1.0"
ahash = { version = "0.8.3", features = ["compile-time-rng"] }

[dev-dependencies]
clap = "4.2.7"
affinity = "0.1.2"
